#!/bin/bash

set -xe

CMD="$1"
shift

function run()
{
	f2c_create_db --dest=/src/fill-db/ --sqlite=/src/fill-db/conf_file_map.sqlite --sqlite-create "$@"
}

case "$CMD" in
	run) run "$@" ;;
	shell) exec /bin/bash ;;
esac
