services:
  clang-struct:
    build: .
    stdin_open: true
    tty: true
    environment:
      CCACHE_MAXSIZE: 20G
      CCACHE_DIR: /src/ccache
    volumes:
      - type: bind
        source: /dev/shm/jslaby/
        target: /src/
      - type: bind
        source: home
        target: /home/jslaby
    depends_on:
      - clang-struct-mariadb
    #links:
    #  - "clang-struct-mariadb:db"

  clang-struct-mariadb:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: xxx
    ports:
      - "30000:3306"
#    volumes:
#      - type: bind
#        source: mariadb/
#        target: /var/lib/mysql/
#        bind: {
#          selinux: Z
#        }
