#!/bin/bash

set -xe

CMD="$1"
shift

function build()
{
	cd /src/linux-cl
	make O=../cl CC='clang' -j160 compile_commands.json
}

function run()
{
	cd /src/cl
	rm structs.db || true
	time run_commands.pl -b ../linux-cl/ "$@"
}

case "$CMD" in
	all) build && run "$@" ;;
	build) build ;;
	run) run "$@" ;;
	shell) exec /bin/bash ;;
esac
