#!/bin/bash

set -xe

CMD="$1"
shift

function build()
{
	cd /src/linux-cl
	export KBUILD_BUILD_TIMESTAMP="$(git show -s --format=%cD)"
	export KBUILD_BUILD_USER=geeko
	export KBUILD_BUILD_HOST=buildhost
	make O=../cl CC='clang' -j160 compile_commands.json
}

function run()
{
	cd /src/cl
	time run_commands.pl --db-host=clang-struct-mariadb -b ../linux-cl/ "$@"
}

function createdb()
{
	cat /home/jslaby_loc/clang-struct-install/usr/local/share/mariadb_create.sql
	mariadb -uroot -pxxx -hclang-struct-mariadb -P0 < /home/jslaby_loc/clang-struct-install/usr/local/share/mariadb_create.sql
}

case "$CMD" in
	all) build && run "$@" ;;
	build) build ;;
	createdb) createdb ;;
	run) run "$@" ;;
	shell) exec /bin/bash ;;
esac
