#!/bin/bash

echo Running with:
git -C /dev/shm/jslaby/linux-cl show @:Makefile | head -4 | tail -3
echo
echo -n "OK? "
read

if [ "$#" -eq 0 ]; then
	set -- all --silent
fi

exec docker-compose run clang-struct "$@"
